#!/usr/bin/env python3
"""
ICS-SimLab Extended — Orchestrator

Reads ctf-config.yaml and generates:
  infrastructure/networks/docker-compose.yml   shared zone networks (bring up first)
  zones/enterprise/docker-compose.yml
  zones/operational/docker-compose.yml
  zones/control/docker-compose.yml             9 custom containers (turbine PLC, HMI, IEDs, actuators)
  start.sh
  stop.sh

Usage:
    python orchestrator/generate.py [ctf-config.yaml]
"""

import os
import sys
import re
import logging
import yaml
from pathlib import Path

logging.basicConfig(level=logging.INFO, format="%(levelname)s - %(message)s")

REPO_ROOT = Path(__file__).resolve().parent.parent
ORCHESTRATOR_DIR = Path(__file__).resolve().parent
ZONES_DIR = REPO_ROOT / "zones"
INFRA_DIR = REPO_ROOT / "infrastructure"
FIREWALL_RULES = ORCHESTRATOR_DIR / "firewall-rules.txt"
ADVERSARY_README = ORCHESTRATOR_DIR / "adversary-readme.txt"

# Maps implementation names to the directory containing their Dockerfile.
# Adding a new component variant means adding an entry here and a Dockerfile.
COMPONENT_DIRS = {
    # enterprise zone
    "win95-era":               ZONES_DIR / "enterprise" / "components" / "legacy-workstation",
    "enterprise-generic":      ZONES_DIR / "enterprise" / "components" / "enterprise-workstation",
    # operational zone
    "historian-v1":            ZONES_DIR / "operational" / "components" / "historian",
    "scada-generic":           ZONES_DIR / "operational" / "components" / "scada-server",
    "engineering-workstation-generic": ZONES_DIR / "operational" / "components" / "engineering-workstation",
    # control zone devices
    "turbine-plc":             ZONES_DIR / "control" / "components" / "turbine-plc",
    "ied-relay":               ZONES_DIR / "control" / "components" / "ied-relay",
    "ied-meter":               ZONES_DIR / "control" / "components" / "ied-meter",
    "hmi":                     ZONES_DIR / "control" / "components" / "hmi",
    "actuator":                ZONES_DIR / "control" / "components" / "actuator",
    # field devices (deferred — vendor-specific builds)
}


# ---------------------------------------------------------------------------
# Start / stop scripts (static constants — do not customise per-config)
# ---------------------------------------------------------------------------

_START_SH = """\
#!/usr/bin/env bash
# Generated by orchestrator/generate.py — do not edit directly.
set -euo pipefail
REPO="$(cd "$(dirname "$0")" && pwd)"

echo "[*] Creating shared networks..."
docker compose -f "$REPO/infrastructure/networks/docker-compose.yml" up -d

echo "[*] Starting enterprise zone..."
docker compose -f "$REPO/zones/enterprise/docker-compose.yml" up -d

echo "[*] Starting operational zone..."
docker compose -f "$REPO/zones/operational/docker-compose.yml" up -d

echo "[*] Starting control zone..."
docker compose -f "$REPO/zones/control/docker-compose.yml" up -d

echo "[*] Applying inter-zone firewall rules..."
if [ "$EUID" -eq 0 ]; then
    bash "$REPO/infrastructure/firewall.sh"
else
    echo "[!] Skipping firewall rules — not root (run as root or with sudo to enforce inter-zone policy)"
fi

echo "[+] All zones running."
"""

_STOP_SH = """\
#!/usr/bin/env bash
# Generated by orchestrator/generate.py — do not edit directly.
set -euo pipefail
REPO="$(cd "$(dirname "$0")" && pwd)"

echo "[*] Stopping control zone..."
docker compose -f "$REPO/zones/control/docker-compose.yml" down

echo "[*] Stopping operational zone..."
docker compose -f "$REPO/zones/operational/docker-compose.yml" down

echo "[*] Stopping enterprise zone..."
docker compose -f "$REPO/zones/enterprise/docker-compose.yml" down

echo "[*] Removing shared networks..."
docker compose -f "$REPO/infrastructure/networks/docker-compose.yml" down

echo "[*] Flushing inter-zone firewall rules..."
if [ "$EUID" -eq 0 ]; then
    iptables -F DOCKER-USER
    iptables -A DOCKER-USER -j RETURN
else
    echo "[!] Skipping firewall flush — not root (run as root or with sudo to flush rules)"
fi

echo "[+] All zones stopped."
"""


# ---------------------------------------------------------------------------
# Config loading
# ---------------------------------------------------------------------------

def load_config(config_path: Path) -> dict:
    with open(config_path) as f:
        raw = f.read()
    # First pass: parse to get values for template resolution
    partial = yaml.safe_load(raw)
    # Second pass: resolve {{ key.path }} references, then re-parse
    rendered = _render_templates(raw, partial)
    return yaml.safe_load(rendered)


def _render_templates(text: str, config: dict) -> str:
    """Replace {{ dotted.key.path }} references with resolved values from config."""
    def resolve(match):
        path = match.group(1).strip().split(".")
        val = config
        for key in path:
            if isinstance(val, dict) and key in val:
                val = val[key]
            else:
                return match.group(0)  # leave unresolved rather than fail
        return str(val)
    return re.sub(r"\{\{([^}]+)\}\}", resolve, text)


# ---------------------------------------------------------------------------
# Path helpers
# ---------------------------------------------------------------------------

def _rel(abs_path, base_dir: Path) -> str:
    """Relative path from base_dir to abs_path."""
    return os.path.relpath(str(abs_path), str(base_dir))


def _relativize_services(services: dict, base_dir: Path, resolve_base: Path = None) -> None:
    """Convert build contexts and bind-mount host paths to relative to base_dir.

    If resolve_base is given, existing relative paths are resolved against it
    before being made relative to base_dir — enabling re-relativization from
    one base directory to another.
    """
    def _fix(path_str: str) -> str:
        if not os.path.isabs(path_str):
            if resolve_base is None:
                return path_str
            path_str = str((resolve_base / path_str).resolve())
        return _rel(path_str, base_dir)

    for svc in services.values():
        # build: "/abs/path"  or  build: {context: "/abs/path"}
        if isinstance(svc.get("build"), str):
            svc["build"] = _fix(svc["build"])
        elif isinstance(svc.get("build"), dict) and "context" in svc["build"]:
            svc["build"]["context"] = _fix(svc["build"]["context"])
        # volumes: ["host_path:container_path", ...]
        fixed = []
        for vol in svc.get("volumes", []):
            if isinstance(vol, str) and ":" in vol:
                host, rest = vol.split(":", 1)
                fixed.append(f"{_fix(host)}:{rest}")
            else:
                fixed.append(vol)
        if fixed:
            svc["volumes"] = fixed


# ---------------------------------------------------------------------------
# Network helpers
# ---------------------------------------------------------------------------

def _net(config: dict, key: str) -> str:
    return config["networks"][key]["docker_name"]


def _subnet(config: dict, key: str) -> str:
    return config["networks"][key]["subnet"]


def _external_net(name: str) -> dict:
    return {"external": True, "name": name}


# ---------------------------------------------------------------------------
# Shared networks compose (must start before zone stacks)
# ---------------------------------------------------------------------------

def generate_networks_compose(config: dict) -> dict:
    net_names = [n["docker_name"] for n in config["networks"].values()]
    networks = {}
    for net_cfg in config["networks"].values():
        name = net_cfg["docker_name"]
        networks[name] = {
            "driver": "bridge",
            "name": name,
            "ipam": {"config": [{"subnet": net_cfg["subnet"]}]},
        }
    return {
        "services": {
            "network-init": {
                "image": "alpine:3.19",
                "command": ["/bin/true"],
                "restart": "no",
                "networks": net_names,
            }
        },
        "networks": networks,
    }


# ---------------------------------------------------------------------------
# Enterprise zone
# ---------------------------------------------------------------------------

def generate_enterprise_compose(config: dict, output_path: Path) -> dict:
    ez = config["enterprise_zone"]
    ent_net = _net(config, "enterprise")
    ops_net = _net(config, "operational")
    base_dir = output_path.parent
    services = {}

    # Legacy workstation — enterprise network only.
    # Runs its own services as-built; attack surface is a property of the
    # implementation, not of this config.
    lw = ez["legacy_workstation"]
    _check_impl(lw["implementation"])
    services["legacy-workstation"] = {
        "build": {"context": _rel(COMPONENT_DIRS[lw["implementation"]], base_dir)},
        "container_name": "legacy-workstation",
        "hostname": lw["hostname"],
        "restart": "unless-stopped",
        "networks": {ent_net: {"ipv4_address": lw["ip"]}},
        "cap_add": ["NET_ADMIN"],
    }

    # Enterprise workstation — sits on enterprise AND operational networks.
    # This is the IT/OT convergence point. Dual-homed by design (or rather,
    # by the gradual accumulation of "temporary" network access never revoked).
    ew = ez["enterprise_workstation"]
    _check_impl(ew["implementation"])
    services["enterprise-workstation"] = {
        "build": {"context": _rel(COMPONENT_DIRS[ew["implementation"]], base_dir)},
        "container_name": "enterprise-workstation",
        "hostname": ew["hostname"],
        "restart": "unless-stopped",
        "networks": {
            ent_net: {"ipv4_address": ew["ip"]},
            ops_net: {"ipv4_address": ew["ops_ip"]},
        },
        "cap_add": ["NET_ADMIN"],
    }

    return {
        "services": services,
        "networks": {
            ent_net: _external_net(ent_net),
            ops_net: _external_net(ops_net),
        },
    }


# ---------------------------------------------------------------------------
# Operational zone
# ---------------------------------------------------------------------------

def generate_operational_compose(config: dict, output_path: Path) -> dict:
    oz = config["operational_zone"]
    ops_net = _net(config, "operational")
    ctrl_net = _net(config, "control")
    base_dir = output_path.parent
    services = {}

    # Historian — operational network only, reachable from enterprise-workstation
    # via its dual-homed ops_ip.
    hist = oz["historian"]
    _check_impl(hist["implementation"])
    services["historian"] = {
        "build": {"context": _rel(COMPONENT_DIRS[hist["implementation"]], base_dir)},
        "container_name": "historian",
        "hostname": hist["hostname"],
        "restart": "unless-stopped",
        "networks": {ops_net: {"ipv4_address": hist["ip"]}},
        "environment": {
            # Tells the historian which ICS process data to seed at startup.
            # Affects what time-series data is available and what queries return.
            "DATA_SOURCE": hist.get("data_source", config["ics_process"]),
        },
    }

    # SCADA server — operational network only, pulls aggregated data from historian.
    scada = oz["scada_server"]
    _check_impl(scada["implementation"])
    services["scada-server"] = {
        "build": {"context": _rel(COMPONENT_DIRS[scada["implementation"]], base_dir)},
        "container_name": "scada-server",
        "hostname": scada["hostname"],
        "restart": "unless-stopped",
        "networks": {ops_net: {"ipv4_address": scada["ip"]}},
        "environment": {
            "HISTORIAN_IP": scada.get("historian_ip", hist["ip"]),
        },
    }

    # Engineering workstation — sits on BOTH operational AND control networks.
    # The pivot point into the control zone.
    eng = oz["engineering_workstation"]
    _check_impl(eng["implementation"])
    services["engineering-workstation"] = {
        "build": {"context": _rel(COMPONENT_DIRS[eng["implementation"]], base_dir)},
        "container_name": "engineering-workstation",
        "hostname": eng["hostname"],
        "restart": "unless-stopped",
        "networks": {
            ops_net: {"ipv4_address": eng["ip"]},
            ctrl_net: {"ipv4_address": eng["ctrl_ip"]},
        },
        "environment": {
            # ICS_PROCESS and CONTROL_SUBNET drive what the engineering-workstation
            # has configured: which device IPs are in its config files, what
            # tools are set up, etc.
            "ICS_PROCESS":      eng.get("ics_process", config["ics_process"]),
            "CONTROL_SUBNET":   eng.get("control_network_subnet", _subnet(config, "control")),
        },
        "cap_add": ["NET_ADMIN"],
    }

    return {
        "services": services,
        "networks": {
            ops_net: _external_net(ops_net),
            ctrl_net: _external_net(ctrl_net),
        },
    }


# ---------------------------------------------------------------------------
# Control zone (native — no external simulator dependency)
# ---------------------------------------------------------------------------

def generate_control_compose(config: dict, output_path: Path) -> dict:
    ctrl_net = _net(config, "control")
    base_dir = output_path.parent
    services = {}

    for dev in config.get("control_zone", {}).get("devices", []):
        impl = dev["implementation"]
        _check_impl(impl)
        svc_name = dev["name"].replace("_", "-")
        svc = {
            "build": {"context": _rel(COMPONENT_DIRS[impl], base_dir)},
            "container_name": dev["name"],
            "hostname": dev.get("hostname", dev["name"]),
            "restart": "unless-stopped",
            "networks": {ctrl_net: {"ipv4_address": dev["ip"]}},
        }
        if dev.get("env"):
            svc["environment"] = dev["env"]
        services[svc_name] = svc

    return {
        "services": services,
        "networks": {ctrl_net: _external_net(ctrl_net)},
    }


# ---------------------------------------------------------------------------
# Inter-zone firewall (DOCKER-USER chain, applied on the host after zones up)
# ---------------------------------------------------------------------------

def generate_firewall_sh(config: dict) -> str:
    """Generate infrastructure/firewall.sh from orchestrator/firewall-rules.txt.

    The rules file contains iptables commands with {placeholder} addresses.
    Placeholders are resolved from ctf-config.yaml and substituted here.
    Edit firewall-rules.txt to change policy; run 'make generate' afterwards.
    """
    addrs = {
        "internet":    config["networks"]["internet"]["subnet"],
        "enterprise":  config["networks"]["enterprise"]["subnet"],
        "operational": config["networks"]["operational"]["subnet"],
        "control":     config["networks"]["control"]["subnet"],
        "wan":         config["networks"]["wan"]["subnet"],
        "historian":   config["operational_zone"]["historian"]["ip"],
        "scada":       config["operational_zone"]["scada_server"]["ip"],
        "eng_ws":      config["operational_zone"]["engineering_workstation"]["ip"],
    }
    # Strip comment header lines from the rules file — the generated script
    # has its own header; the txt file comments are for human editors only.
    raw = FIREWALL_RULES.read_text()
    body = "\n".join(
        line for line in raw.splitlines() if not line.startswith("#")
    ).strip()
    rules = body.format_map(addrs)
    return (
        "#!/usr/bin/env bash\n"
        "# Inter-zone firewall rules — DOCKER-USER chain\n"
        "# Generated by orchestrator/generate.py — do not edit directly.\n"
        "# Edit orchestrator/firewall-rules.txt to change policy.\n"
        "#\n"
        "# Requires root (iptables). Applied after all zone stacks are up.\n"
        "set -euo pipefail\n"
        "\n"
        'if [ "$EUID" -ne 0 ]; then\n'
        '    echo "[firewall] Error: iptables rules require root. Run as root or with sudo." >&2\n'
        "    exit 1\n"
        "fi\n"
        "\n"
        "iptables -F DOCKER-USER\n"
        "\n"
        + rules
        + '\necho "[firewall] Inter-zone rules applied."\n'
    )




# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _check_impl(name: str) -> None:
    if name not in COMPONENT_DIRS:
        raise ValueError(
            f"Unknown implementation/vendor: {name!r}. "
            f"Known: {list(COMPONENT_DIRS)}"
        )


def write_compose(path: Path, compose_dict: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w") as f:
        yaml.dump(compose_dict, f, sort_keys=False, default_flow_style=False)
    logging.info(f"Wrote: {path}")


def write_script(path: Path, content: str) -> None:
    path.write_text(content)
    path.chmod(0o755)
    logging.info(f"Wrote: {path}")


def write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    logging.info(f"Wrote: {path}")


# ---------------------------------------------------------------------------
# Jump host
# ---------------------------------------------------------------------------

def generate_adversary_readme(config: dict) -> str:
    addrs = {
        "enterprise_subnet": config["networks"]["enterprise"]["subnet"],
        "legacy_ws_ip":      config["enterprise_zone"]["legacy_workstation"]["ip"],
        "ent_ws_ip":         config["enterprise_zone"]["enterprise_workstation"]["ip"],
    }
    return ADVERSARY_README.read_text().format_map(addrs)


def generate_jump_host_compose(config: dict, output_path: Path) -> dict:
    inet_net = _net(config, "internet")
    ent_net = _net(config, "enterprise")
    jh = config["jump_host"]
    ssh_host_port = jh.get("ssh_host_port", 22)
    return {
        "services": {
            "jump-host": {
                "build": {"context": "."},   # relative to compose file dir
                "container_name": "jump-host",
                "hostname": jh["hostname"],
                "restart": "unless-stopped",
                "networks": {
                    inet_net: {"ipv4_address": jh["internet_ip"]},
                    ent_net:  {"ipv4_address": jh["ip"]},
                },
                "ports": [f"{ssh_host_port}:22"],
                "volumes": [
                    "./adversary-keys:/run/adversary-keys:ro",
                    "./adversary-readme.txt:/run/adversary-readme.txt:ro",
                ],
            }
        },
        "networks": {
            inet_net: _external_net(inet_net),
            ent_net:  _external_net(ent_net),
        },
    }


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    config_path = (
        Path(sys.argv[1]) if len(sys.argv) > 1
        else ORCHESTRATOR_DIR / "ctf-config.yaml"
    )

    logging.info(f"Loading config: {config_path}")
    config = load_config(config_path)

    write_compose(
        INFRA_DIR / "networks" / "docker-compose.yml",
        generate_networks_compose(config),
    )

    enterprise_path  = ZONES_DIR / "enterprise"  / "docker-compose.yml"
    operational_path = ZONES_DIR / "operational" / "docker-compose.yml"
    control_path     = ZONES_DIR / "control"     / "docker-compose.yml"

    write_compose(enterprise_path,  generate_enterprise_compose(config, enterprise_path))
    write_compose(operational_path, generate_operational_compose(config, operational_path))
    write_compose(control_path,     generate_control_compose(config, control_path))

    write_script(REPO_ROOT / "start.sh", _START_SH)
    write_script(REPO_ROOT / "stop.sh", _STOP_SH)
    write_script(INFRA_DIR / "firewall.sh", generate_firewall_sh(config))

    jump_host_path = INFRA_DIR / "jump-host" / "docker-compose.yml"
    write_compose(jump_host_path, generate_jump_host_compose(config, jump_host_path))
    write_text(INFRA_DIR / "jump-host" / "adversary-readme.txt", generate_adversary_readme(config))

    logging.info("Done. Run: bash start.sh")


if __name__ == "__main__":
    main()
