#!/usr/bin/env bash
# Inter-zone firewall rules — DOCKER-USER chain
# Generated by orchestrator/generate.py — do not edit directly.
# Edit orchestrator/firewall-rules.txt to change policy.
#
# Requires root (iptables). Applied after all zone stacks are up.
set -euo pipefail

if [ "$EUID" -ne 0 ]; then
    echo "[firewall] Error: iptables rules require root. Run as root or with sudo." >&2
    exit 1
fi

iptables -F DOCKER-USER

iptables -A DOCKER-USER -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT

iptables -A DOCKER-USER -s 10.10.0.0/24 -d 10.10.1.0/24 -j DROP
iptables -A DOCKER-USER -s 10.10.0.0/24 -d 10.10.2.0/24 -j DROP
iptables -A DOCKER-USER -s 10.10.0.0/24 -d 10.10.3.0/24 -j DROP
iptables -A DOCKER-USER -s 10.10.0.0/24 -d 10.10.4.0/24 -j DROP

iptables -A DOCKER-USER -s 10.10.1.0/24 -d 10.10.2.10 -p tcp --dport 8080 -j ACCEPT
iptables -A DOCKER-USER -s 10.10.1.0/24 -d 10.10.2.20 -p tcp --dport 8080 -j ACCEPT
iptables -A DOCKER-USER -s 10.10.1.0/24 -d 10.10.2.30 -p tcp --dport 22 -j ACCEPT
iptables -A DOCKER-USER -s 10.10.1.0/24 -d 10.10.2.0/24 -j DROP

iptables -A DOCKER-USER -s 10.10.1.0/24 -d 10.10.3.0/24 -j DROP
iptables -A DOCKER-USER -s 10.10.1.0/24 -d 10.10.4.0/24 -j DROP

iptables -A DOCKER-USER -s 10.10.2.30 -d 10.10.3.0/24 -p tcp --dport 502 -j ACCEPT
iptables -A DOCKER-USER -s 10.10.2.0/24 -d 10.10.3.0/24 -j DROP

iptables -A DOCKER-USER -s 10.10.2.20 -d 10.10.4.0/24 -p tcp --dport 502 -j ACCEPT
iptables -A DOCKER-USER -s 10.10.2.30 -d 10.10.4.0/24 -p tcp --dport 502 -j ACCEPT
iptables -A DOCKER-USER -s 10.10.2.20 -d 10.10.4.0/24 -p udp --dport 161 -j ACCEPT
iptables -A DOCKER-USER -s 10.10.2.30 -d 10.10.4.0/24 -p udp --dport 161 -j ACCEPT
iptables -A DOCKER-USER -s 10.10.2.0/24 -d 10.10.4.0/24 -j DROP

iptables -A DOCKER-USER -s 10.10.3.0/24 -d 10.10.1.0/24 -j DROP
iptables -A DOCKER-USER -s 10.10.3.0/24 -d 10.10.2.0/24 -j DROP

iptables -A DOCKER-USER -s 10.10.4.0/24 -d 10.10.0.0/24 -j DROP
iptables -A DOCKER-USER -s 10.10.4.0/24 -d 10.10.1.0/24 -j DROP
iptables -A DOCKER-USER -s 10.10.4.0/24 -d 10.10.2.0/24 -j DROP
iptables -A DOCKER-USER -s 10.10.4.0/24 -d 10.10.3.0/24 -j DROP

iptables -A DOCKER-USER -j RETURN
echo "[firewall] Inter-zone rules applied."
