rocommunity  public
rwcommunity  private

sysDescr     MTR-100 Revenue Meter, Hex Computing Division, firmware 1.3.0
sysContact   Ponder Stibbons <ponder@unseen.edu>
sysLocation  Main Feed, Unseen University Power Plant
sysName      uupl-meter

master off
agentAddress udp:161
